name: Update Readme on PR

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run script to update readme
      run: |
        OUTPUT_FOLDER=output
        README_FILE=$OUTPUT_FOLDER/readme.txt

        # Create output folder if it doesn't exist
        mkdir -p $OUTPUT_FOLDER

        # Get the PR title and description
        PR_TITLE=$(git log -1 --pretty=%s)
        PR_DESCRIPTION=$(git log -1 --pretty=%b)

        # Append PR information to readme.txt
        echo "### PR Title: $PR_TITLE" >> $README_FILE
        echo "PR Description:" >> $README_FILE
        echo "$PR_DESCRIPTION" >> $README_FILE
        echo "------------------------------" >> $README_FILE

        echo "PR information appended to readme.txt."

        # Create and checkout a new branch
        git checkout -b update-readme-branch

        # Commit changes
        git add $OUTPUT_FOLDER
        git commit -m "Update readme with PR information"

        # Push changes to the new branch
        git push origin update-readme-branch

      working-directory: ${{ github.workspace }}

